#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#       dml - the drama markup language
#       
#       Copyright 2010 Christian Schramm <christian.h.m.schramm@gmail.com>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

from optparse import OptionParser

import sinks

if __name__ == '__main__':
        
    option_parser = OptionParser(usage="dml [options] FILE")
    add_option = option_parser.add_option
    sink_mods = [sinks.__dict__[mod] for mod in sinks.__all__]
    for mod in sink_mods:
        add_option("-" + mod.VERYSHORTNAME, "--" + mod.SHORTNAME,
                   dest=mod.SHORTNAME, action="store_true",
                   default=False, help=mod.DESCRIPTION)
    add_option("-q", "--quiet", action="store_false", dest="verbose",
               default=True, help="don't print status messages to stdout")
    (options, args) = option_parser.parse_args()
    if not args:
        parser.print_help()
        import sys
        sys.exit(2)

    from src import main
    main.main(args[0], options)
